/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Options {
  createIfMissing: boolean
  keepLogFileNum: number
}
export function connect(path: string, opts: Options, abortSignal?: AbortSignal | undefined | null): Promise<number>
export function getItem(dbId: number, key: string, abortSignal?: AbortSignal | undefined | null): Promise<string | null>
export function setItem(dbId: number, key: string, value: string, abortSignal?: AbortSignal | undefined | null): Promise<void>
export function getKeys(dbId: number, prefix?: string | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<Array<string>>
export function removeItem(dbId: number, key: string, abortSignal?: AbortSignal | undefined | null): Promise<void>
export function close(dbId: number, abortSignal?: AbortSignal | undefined | null): Promise<void>
